var movieTitle = "Amadeus";
movieTitle = "Arrival";
movieTitle = 9; //not allowed
var numCatLives = 9;
numCatLives += 1;
numCatLives = "zero"; // we cannot assign string to variable from type number
var gameOVer = false;
gameOVer = true;
gameOVer = "true"; // not allowed to assign string
